import './globals.css'
import NavBarSolid from './_components/NavBarSolid'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <NavBarSolid/>
        {children}
        </body>
    </html>
  )
}
