import './globals.css'
import NavBarSolid from './_components/NavBarSolid'
import Footer from './_components/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col justify-between">
        <NavBarSolid/>
        <div className="bg-white flex-grow min-h-64">
        {children} 
        </div>
        <Footer/>
        </body>
    </html>
  )
}
