import { Inter } from 'next/font/google'
import TransparentNavBar from '@/app/_components/transparentNavBar'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-center items-center">
        <TransparentNavBar/>
        <h1> Home Layout</h1>
        {children}</body>
    </html>
  )
}
