import Footer from "../_components/Footer";
import TransparentNavBar from "../_components/transparentNavBar";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-center items-center font-body">
        <TransparentNavBar />
        <div className="bg-black flex flex-col min-h-64 w-full mt-[-127px] bg-gradient-to-t from-neutral-950 to-neutral-800">
        {children} 
        </div>
        <Footer/>
      </body>
    </html>
  );
}
