import Footer from "../../../_components/Footer";
import TransparentNavBar from "../../../_components/transparentNavBar";
import "../../../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ExclusiveListingLayout({ children }) {
  return (
    <>
  
    {children}
   
  </>
  );
}
