import "../globals.css";
import NavBarSolid from "../_components/NavBarSolid";
import Footer from "../_components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <link
      href="https://api.tiles.mapbox.com/mapbox-gl-js/v3.1.0/mapbox-gl.css"
      rel="stylesheet"
      precedence="default"
    />
    <body className="min-h-screen flex flex-col justify-between">
      <NavBarSolid />
      <div className="bg-white flex-grow min-h-64">{children}</div>
      <Footer />
    </body></html>
  );
}
